version: "3.2"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "127.0.0.1:8100:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/create_database.sql
